### ISSUE TITLE
Figure out a way to test with/without certain packages in CI

### ISSUE THREAD

**Issue by gaogaotiantian** [gaogaotiantian/viztracer#197]
We've been gradually adding supports for optional packages, for example, orjson, loky, trio ... We want to test VizTracer in environments with and without the packages both. In the future, maybe even package matrices.

We don't want to do this with github actions matrix as the majority of the tests only needs to run in a single environment. Repeating them will take too long.

Ideally, we can create a decorator that could be added on a single test, telling the test to run with and without certain packages.

```
@package_matrix(["orjson"])
def test_orjson(self):
    ...
```

We can put the nasty installing/uninstalling stuff in the decorator.

In order to not messing with the developer's dev-environment, we probably need another decorator to ask the test to be skipped if it's not in github actions. Maybe a single ``skipIf`` with ``os.getenv`` would do. I'll see how messy is the code.

**Comment by richardsheridan** [comment]
What about [including](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-new-combinations) extra package combinations, rather than directly putting them in the matrix definition? Then the test code could simply do `@skipIf(importlib.util.find_spec(...))` or `pytest.importorskip(...)` as appropriate, and only one chosen platform will execute the test for each optional package. Example yaml:

```yaml
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
            - python-version: '3.10'
              os: ubuntu-latest
              trio: true
            - python-version: '3.10'
              os: ubuntu-latest
              orjson: true
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r requirements-dev.txt
    - name: Install trio dependencies
      if: matrix.trio
      run: pip install trio
    - name: Install orjson dependencies
      if: matrix.orjson
      run: pip install orjson
```

This will unfortunately run all tests for each optional extra but as I said, only on one platform. To cut that down you could layer `@pytest.mark.trio` decorators and `pytest -m trio` on top of this, but I don't know enough about tox to show how do that.
